import React, { useMemo, useState } from 'react';
import { AlertTriangle, Download, Play, RefreshCw, Save, Settings2, Sparkles } from 'lucide-react';
import { AssignmentWarning, CurrentShiftState, NurseStaff, OperationalEvent, PatientRoom, StaffStatus } from '../types';
import { runRecommendationEngine } from '../services/recommendationEngine';
import { postProcessRecommendation } from '../services/recommendationPostProcessor';
import { StorageService } from '../services/storage';
import { CurrentRosterPanel } from './CurrentRosterPanel';
import { FloorPlanCurrentStaffing } from './FloorPlanCurrentStaffing';
import { OperationalSnapshot } from './OperationalSnapshot';
import { RecommendationOption, RecommendationOptions } from './RecommendationOptions';

interface Props { currentShift:CurrentShiftState; onCurrentShiftChange:(state:CurrentShiftState)=>void; events:OperationalEvent[]; onEventsChange:(events:OperationalEvent[])=>void; onStartFromPlan:()=>void; }
const fmtTime=(iso:string)=>new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
const csvCell=(value:unknown)=>`"${String(value ?? '').replace(/"/g,'""')}"`;

export const CurrentStaffing:React.FC<Props>=({currentShift,onCurrentShiftChange,events,onEventsChange,onStartFromPlan})=>{
 const [warnings,setWarnings]=useState<AssignmentWarning[]>([]),[unassigned,setUnassigned]=useState<string[]>([]),[fitLabel,setFitLabel]=useState('NOT RUN'),[showRoster,setShowRoster]=useState(false),[recommendationOptions,setRecommendationOptions]=useState<RecommendationOption[]>([]),[semiAutoActive,setSemiAutoActive]=useState(false);
 const census=currentShift.rooms.filter(r=>r.isOccupied).length;
 const activeRNs=currentShift.roster.filter(s=>['RN','Preceptor'].includes(s.role)&&['ACTIVE','RECALLED'].includes(s.staffStatus)).length;
 const reserve=currentShift.roster.filter(s=>['ON_CALL','FLEXED'].includes(s.staffStatus)).length;
 const rosterNames=Object.fromEntries(currentShift.roster.map(s=>[s.id,s.name]));
 const fixedAssignments=Object.fromEntries(currentShift.rooms.filter(r=>r.isOccupied&&r.assignedNurseId).map(r=>[r.roomNumber,r.assignedNurseId as string]));
 const fixedRoomNumbers=Object.keys(fixedAssignments);
 const liveUnassigned=currentShift.rooms.filter(r=>r.isOccupied&&!r.assignedNurseId).length;

 const appendEvent=(e:OperationalEvent)=>{StorageService.appendOperationalEvent(e);onEventsChange(StorageService.loadOperationalEvents());};
 const saveState=(next:CurrentShiftState)=>{const stamped={...next,lastUpdatedAt:new Date().toISOString()};StorageService.saveCurrentShift(stamped);onCurrentShiftChange(stamped);};
 const updateShiftIdentity=(patch:Partial<Pick<CurrentShiftState,'date'|'shiftType'>>)=>{saveState({...currentShift,...patch});setRecommendationOptions([]);setWarnings([]);setUnassigned([]);setFitLabel('NOT RUN');};
 const updateRoster=(roster:NurseStaff[])=>{const ids=new Set(roster.map(s=>s.id));saveState({...currentShift,roster,rooms:currentShift.rooms.map(r=>r.assignedNurseId&&!ids.has(r.assignedNurseId)?{...r,assignedNurseId:null}:r)});};
 const updateRoom=(updated:PatientRoom)=>{const before=currentShift.rooms.find(r=>r.roomNumber===updated.roomNumber);saveState({...currentShift,rooms:currentShift.rooms.map(r=>r.roomNumber===updated.roomNumber?updated:r)});if(before&&before.acuity!==updated.acuity)appendEvent({id:`evt-${Date.now()}-acuity`,timestamp:new Date().toISOString(),shiftDate:currentShift.date,shiftType:currentShift.shiftType,type:'ACUITY_CHANGE',roomNumber:updated.roomNumber,summary:`Room ${updated.roomNumber} acuity changed ${before.acuity} → ${updated.acuity}.`});if(before&&before.flags.join('|')!==updated.flags.join('|'))appendEvent({id:`evt-${Date.now()}-flags`,timestamp:new Date().toISOString(),shiftDate:currentShift.date,shiftType:currentShift.shiftType,type:'ROOM_FLAGS_CHANGE',roomNumber:updated.roomNumber,summary:`Room ${updated.roomNumber} flags updated: ${updated.flags.join(', ')||'none'}.`});};
 const assignRoom=(roomNumber:string,nurseId:string|null)=>{saveState({...currentShift,rooms:currentShift.rooms.map(r=>r.roomNumber===roomNumber?{...r,assignedNurseId:nurseId}:r)});appendEvent({id:`evt-${Date.now()}`,timestamp:new Date().toISOString(),shiftDate:currentShift.date,shiftType:currentShift.shiftType,type:'ASSIGNMENT_CHANGE',roomNumber,summary:`Room ${roomNumber} ${nurseId?'assigned':'unassigned'}.`});};
 const recallPreviousAssignments=()=>{};
 const updateStatus=(staff:NurseStaff,status:StaffStatus)=>saveState({...currentShift,roster:currentShift.roster.map(s=>s.id===staff.id?{...s,staffStatus:status}:s)});
 const updateSupport=(kind:'MT'|'PCT',value:string)=>saveState(kind==='MT'?{...currentShift,mtState:value as CurrentShiftState['mtState']}:{...currentShift,pctState:value as CurrentShiftState['pctState']});
 const recommend=(strategy:'BALANCED'|'CONSERVE_SKILL_MIX'|'CAPACITY_EXCEPTION',charge:boolean,quad:boolean,fixed:Record<string,string>={})=>postProcessRecommendation(runRecommendationEngine(currentShift.roster,currentShift.rooms,charge,quad,strategy,fixed),currentShift.roster,currentShift.rooms,Object.keys(fixed));
 const generate=(semiAuto=false)=>{const fixed=semiAuto?fixedAssignments:{};const balanced=recommend('BALANCED',false,false,fixed);const conserve=recommend('CONSERVE_SKILL_MIX',false,false,fixed);const capacityNormal=recommend('CAPACITY_EXCEPTION',false,false,fixed);const capacity=capacityNormal.unassignedRooms.length===0?capacityNormal:recommend('CAPACITY_EXCEPTION',true,true,fixed);const prefix=semiAuto&&fixedRoomNumbers.length?`Keeps ${fixedRoomNumbers.length} CN-set room${fixedRoomNumbers.length===1?'':'s'} fixed, then `:'';setRecommendationOptions([{id:'BALANCED',title:'Balanced / Spread ICU',subtitle:`${prefix}spreads ICU workload when skill mix allows.`,result:balanced},{id:'CONSERVE_SKILL_MIX',title:'Preserve Critical-Care Skill Mix',subtitle:`${prefix}conserves critical-care skill mix when needed.`,result:conserve},{id:'CAPACITY_EXCEPTION',title:'Capacity Exception',subtitle:`${prefix}uses capacity exceptions only when necessary.`,result:capacity}]);setSemiAutoActive(semiAuto);setFitLabel(semiAuto?`SEMI-AUTO • ${fixedRoomNumbers.length} FIXED`:'3 OPTIONS');setWarnings([]);setUnassigned([]);};
 const applyOption=(option:RecommendationOption)=>{const result=option.result;saveState({...currentShift,rooms:currentShift.rooms.map(r=>({...r,assignedNurseId:result.assignments[r.roomNumber]||null}))});setWarnings(result.warnings);setUnassigned(result.unassignedRooms);setFitLabel(result.fitLabel);setRecommendationOptions([]);appendEvent({id:`evt-${Date.now()}-option`,timestamp:new Date().toISOString(),shiftDate:currentShift.date,shiftType:currentShift.shiftType,type:'RECOMMENDATION_GENERATED',summary:`Applied ${semiAutoActive?'Semi-Auto ':''}${option.title}.`});setSemiAutoActive(false);};
 const finalizeShift=()=>{const finalizedAt=new Date().toISOString();StorageService.saveFinalizedShift({id:`actual-${Date.now()}`,date:currentShift.date,shiftType:currentShift.shiftType,finalizedAt,roster:currentShift.roster,rooms:currentShift.rooms,onCall:currentShift.onCall,fitScore:liveUnassigned?Math.max(10,100-liveUnassigned*15):100,warnings,mtState:currentShift.mtState,pctState:currentShift.pctState,currentMRS:0,projectedMRS:0});appendEvent({id:`evt-${Date.now()}-finalize`,timestamp:finalizedAt,shiftDate:currentShift.date,shiftType:currentShift.shiftType,type:'ASSIGNMENT_CHANGE',summary:`Finalized and saved ${currentShift.date} ${currentShift.shiftType} shift.`});setFitLabel('SHIFT SAVED');window.alert(`${currentShift.date} ${currentShift.shiftType} shift saved to History.`);};
 const exportShiftCsv=()=>{const headers=['Shift Date','Shift','Exported At','Room','PatientStayID','Acuity','Flags','Assigned Nurse','Role','Capability','Staff Status','Phone','MT Coverage','PCT Support','Clinical Supervisor'];const rows=currentShift.rooms.filter(r=>r.isOccupied).map(room=>{const nurse=currentShift.roster.find(s=>s.id===room.assignedNurseId);return [currentShift.date,currentShift.shiftType,new Date().toISOString(),room.roomNumber,room.patientStayId,room.acuity,room.flags.join(' | '),nurse?.name||'',nurse?.role||'',nurse?.capability||'',nurse?.staffStatus||'',nurse?.assignedPhone||'',currentShift.mtState,currentShift.pctState,currentShift.clinicalSupervisorPresent?'Present':'Not Present'];});const csv='\ufeff'+[headers,...rows].map(row=>row.map(csvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`1E_Assignment_${currentShift.date}_${currentShift.shiftType}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);};
 const shiftEvents=useMemo(()=>events.filter(e=>e.shiftDate===currentShift.date&&e.shiftType===currentShift.shiftType).slice(0,12),[events,currentShift.date,currentShift.shiftType]);

 return <div className="space-y-3">
  <div className="bg-white border rounded-xl px-3 py-2 flex flex-wrap items-center justify-between gap-2">
   <div className="flex flex-wrap items-center gap-3"><div><div className="text-[10px] font-black uppercase text-slate-500">Quick Assignment</div><div className="text-sm font-black">{currentShift.date} • {currentShift.shiftType} Shift</div></div><div className="text-xs bg-slate-100 rounded px-2 py-1">Census <b>{census}</b></div><div className="text-xs bg-slate-100 rounded px-2 py-1">RNs <b>{activeRNs}</b></div><div className={`text-xs rounded px-2 py-1 ${liveUnassigned?'bg-rose-100 text-rose-800':'bg-emerald-100 text-emerald-800'}`}>Needs RN <b>{liveUnassigned}</b></div></div>
   <div className="text-[10px] text-slate-500">Last updated {fmtTime(currentShift.lastUpdatedAt)}</div>
  </div>

  <FloorPlanCurrentStaffing quickMode currentShift={currentShift} onRoomChange={updateRoom} onAssignRoom={assignRoom} onStaffStatusChange={updateStatus} onRecallPrevious={recallPreviousAssignments}/>

  <details className="bg-white rounded-xl border p-3">
   <summary className="font-black text-xs uppercase cursor-pointer flex items-center gap-2"><Settings2 className="w-4 h-4"/>More tools / setup</summary>
   <div className="mt-4 space-y-4">
    <OperationalSnapshot currentCensus={census} rooms={currentShift.rooms} capacity={22}/>
    <div className="bg-white rounded-xl border p-4 flex flex-wrap justify-between gap-3 items-end"><div className="flex flex-wrap gap-3 items-end"><div><label className="text-[10px] uppercase font-black text-slate-500 block">Current Shift Date</label><input type="date" value={currentShift.date} onChange={e=>updateShiftIdentity({date:e.target.value})} className="border rounded-lg px-3 py-2 text-xs"/></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">Current Shift</label><select value={currentShift.shiftType} onChange={e=>updateShiftIdentity({shiftType:e.target.value as CurrentShiftState['shiftType']})} className="border rounded-lg px-3 py-2 text-xs"><option value="Day">Day</option><option value="Night">Night</option></select></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">MT Coverage</label><select value={currentShift.mtState} onChange={e=>updateSupport('MT',e.target.value)} className="border rounded-lg px-3 py-2 text-xs"><option value="MT_PRESENT">MT Present</option><option value="RN_COVERING_MT">RN Covering MT</option><option value="MT_UNFILLED">MT Unfilled</option></select></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">PCT Support</label><select value={currentShift.pctState} onChange={e=>updateSupport('PCT',e.target.value)} className="border rounded-lg px-3 py-2 text-xs"><option value="PCT_PRESENT">PCT Present</option><option value="PCT_NONE">No PCT</option></select></div><button onClick={()=>setShowRoster(v=>!v)} className="px-3 py-2 rounded-lg border text-xs font-bold flex gap-1"><Settings2 className="w-3.5 h-3.5"/>{showRoster?'Hide':'Edit'} Roster</button><button onClick={onStartFromPlan} className="px-3 py-2 rounded-lg border text-xs font-bold flex gap-1"><RefreshCw className="w-3.5 h-3.5"/>Reset from Saved Plan</button></div><div className="flex flex-wrap gap-2"><button onClick={()=>generate(false)} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Play className="w-3.5 h-3.5"/>Generate 3 Options</button><button disabled={fixedRoomNumbers.length===0} onClick={()=>generate(true)} className="bg-indigo-600 disabled:bg-slate-300 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Sparkles className="w-3.5 h-3.5"/>Semi-Auto Fill Rest</button><button onClick={finalizeShift} className="bg-blue-600 text-white px-3 py-2 rounded-lg text-xs font-bold flex gap-1"><Save className="w-3.5 h-3.5"/>Finalize / Save Shift</button><button onClick={exportShiftCsv} className="bg-white border px-3 py-2 rounded-lg text-xs font-bold flex gap-1"><Download className="w-3.5 h-3.5"/>Export CSV</button></div></div>
    {showRoster&&<CurrentRosterPanel roster={currentShift.roster} onRosterChange={updateRoster}/>} 
    <RecommendationOptions options={recommendationOptions} rosterNames={rosterNames} onApply={applyOption}/>
    {unassigned.length>0&&<div className="bg-rose-50 border border-rose-300 text-rose-900 rounded-xl p-3 flex gap-2"><AlertTriangle className="w-4 h-4 mt-0.5"/><div><b className="text-sm">Auto-assignment needs CN review for {unassigned.join(', ')}.</b></div></div>}
    <details className="bg-slate-50 rounded-xl border p-3"><summary className="font-black text-xs uppercase cursor-pointer">Midshift Operational Event Log</summary><div className="mt-3 space-y-2">{shiftEvents.map(e=><div key={e.id} className="text-xs border-b pb-2"><span className="font-mono text-slate-500 mr-3">{fmtTime(e.timestamp)}</span>{e.summary}</div>)}</div></details>
   </div>
  </details>
 </div>;
};
