import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, Brain, CircleDot, Droplets, HeartPulse, LogIn, LogOut, MoveRight, ShieldAlert, Users, Wind, X } from 'lucide-react';
import floorPlanImage from '../assets/1e-floorplan.png';
import { AcuityLevel, ComplexityFlag, CurrentShiftState, NurseStaff, PatientRoom, StaffStatus } from '../types';

interface Props { currentShift: CurrentShiftState; onRoomChange: (room: PatientRoom) => void; onAssignRoom: (roomNumber: string, nurseId: string | null) => void; onStaffStatusChange: (staff: NurseStaff, status: StaffStatus) => void; }
type RoomPosition = { left: number; top: number };
const ROOM_POSITIONS: Record<string, RoomPosition> = {
  '101':{left:85.2,top:88.8},'102':{left:85.2,top:74.2},'103':{left:85.2,top:61.6},'104':{left:85.2,top:47.8},'105':{left:85.2,top:35.6},'106':{left:85.2,top:17.2},
  '107':{left:54.3,top:24.1},'108':{left:54.3,top:34.1},'109':{left:51.2,top:40.7},'110':{left:58.8,top:59.0},'111':{left:58.8,top:70.2},'112':{left:58.8,top:78.7},'113':{left:57.2,top:88.5},
  '114':{left:18.5,top:88.4},'115':{left:16.5,top:78.2},'116':{left:16.5,top:68.4},'117':{left:15.4,top:59.0},'118':{left:16.3,top:50.5},'119':{left:17.8,top:40.8},'120':{left:17.8,top:33.1},'121':{left:15.0,top:24.2},'122':{left:14.8,top:14.8}
};
const ACUITY_STYLES: Record<AcuityLevel,{badge:string;room:string;dot:string}> = {
  CVICU:{badge:'bg-rose-100 text-rose-800 border-rose-200',room:'bg-rose-200/90 border-rose-500 text-rose-950',dot:'bg-rose-500'},
  ICU:{badge:'bg-orange-100 text-orange-800 border-orange-200',room:'bg-orange-200/90 border-orange-500 text-orange-950',dot:'bg-orange-500'},
  PCU:{badge:'bg-blue-100 text-blue-800 border-blue-200',room:'bg-blue-200/90 border-blue-500 text-blue-950',dot:'bg-blue-500'},
  TELE:{badge:'bg-emerald-100 text-emerald-800 border-emerald-200',room:'bg-emerald-200/90 border-emerald-500 text-emerald-950',dot:'bg-emerald-500'}
};
const FLAGS:{flag:ComplexityFlag;icon:React.ReactNode}[] = [
  {flag:'Vent',icon:<Wind className="w-3.5 h-3.5"/>},{flag:'Pressors',icon:<Activity className="w-3.5 h-3.5"/>},{flag:'Impella/IABP',icon:<HeartPulse className="w-3.5 h-3.5"/>},{flag:'Fresh Post-Op',icon:<CircleDot className="w-3.5 h-3.5"/>},{flag:'HD/Dialysis',icon:<Droplets className="w-3.5 h-3.5"/>},{flag:'Isolation',icon:<ShieldAlert className="w-3.5 h-3.5"/>},{flag:'Sitter/Safety',icon:<Users className="w-3.5 h-3.5"/>},{flag:'High Fall Risk',icon:<AlertTriangle className="w-3.5 h-3.5"/>},{flag:'Confused',icon:<Brain className="w-3.5 h-3.5"/>},{flag:'Admission',icon:<LogIn className="w-3.5 h-3.5"/>},{flag:'Transfer',icon:<MoveRight className="w-3.5 h-3.5"/>},{flag:'Possible DC',icon:<LogOut className="w-3.5 h-3.5"/>},{flag:'Expected DC',icon:<LogOut className="w-3.5 h-3.5"/>},{flag:'Discharge',icon:<LogOut className="w-3.5 h-3.5"/>}
];
const STATUS_STYLES:Record<StaffStatus,string>={ACTIVE:'bg-emerald-100 text-emerald-800 border-emerald-200',FLEXED:'bg-amber-100 text-amber-800 border-amber-200',ON_CALL:'bg-sky-100 text-sky-800 border-sky-200',RECALLED:'bg-violet-100 text-violet-800 border-violet-200'};
const firstName=(name:string)=>name.trim().split(/\s+/)[0]||name;

export const FloorPlanCurrentStaffing:React.FC<Props>=({currentShift,onRoomChange,onAssignRoom,onStaffStatusChange})=>{
  const occupiedRooms=currentShift.rooms.filter(r=>r.isOccupied);
  const unassignedRooms=occupiedRooms.filter(r=>!r.assignedNurseId);
  const [selectedRoomNumber,setSelectedRoomNumber]=useState<string>(()=>occupiedRooms[0]?.roomNumber||'104');
  const [manualStaffId,setManualStaffId]=useState<string|null>(null);
  const selectedRoom=currentShift.rooms.find(r=>r.roomNumber===selectedRoomNumber)||currentShift.rooms[0];
  const assignedNurse=currentShift.roster.find(s=>s.id===selectedRoom?.assignedNurseId);
  const manualStaff=currentShift.roster.find(s=>s.id===manualStaffId)||null;
  const bedsideStaff=useMemo(()=>currentShift.roster.filter(s=>s.role==='RN'||s.role==='CHG'),[currentShift.roster]);
  const setSelectedAcuity=(acuity:AcuityLevel)=>{if(selectedRoom)onRoomChange({...selectedRoom,acuity,isOccupied:true});};
  const toggleFlag=(flag:ComplexityFlag)=>{if(!selectedRoom)return;const exists=selectedRoom.flags.includes(flag);let flags=exists?selectedRoom.flags.filter(f=>f!==flag):[...selectedRoom.flags,flag];if(!exists&&flag==='Expected DC')flags=flags.filter(f=>f!=='Possible DC');if(!exists&&flag==='Possible DC')flags=flags.filter(f=>f!=='Expected DC');onRoomChange({...selectedRoom,flags});};
  const assignedRoomsFor=(staffId:string)=>currentShift.rooms.filter(r=>r.isOccupied&&r.assignedNurseId===staffId);
  const handleRoomClick=(room:PatientRoom)=>{setSelectedRoomNumber(room.roomNumber);if(!manualStaffId||!room.isOccupied)return;onAssignRoom(room.roomNumber,room.assignedNurseId===manualStaffId?null:manualStaffId);};
  const selectStaff=(staff:NurseStaff)=>{if(!['ACTIVE','RECALLED'].includes(staff.staffStatus))return;setManualStaffId(manualStaffId===staff.id?null:staff.id);};

  return <div className="space-y-4"><div className="grid grid-cols-1 2xl:grid-cols-[230px_minmax(0,1fr)_300px] gap-4 items-start">
    <aside className="space-y-3">
      <div className="bg-white border border-slate-200 rounded-xl p-3"><h3 className="font-black text-sm text-slate-800 mb-2">Acuity / Level of Care</h3><div className="space-y-2">{(Object.keys(ACUITY_STYLES) as AcuityLevel[]).map(level=><button type="button" key={level} onClick={()=>setSelectedAcuity(level)} className={`w-full flex items-center gap-2 px-2.5 py-2 rounded-lg border text-xs font-black text-left ${ACUITY_STYLES[level].badge}`}><span className={`w-3.5 h-3.5 rounded-full ${ACUITY_STYLES[level].dot}`}/>{level}</button>)}</div></div>
      <div className="bg-white border border-slate-200 rounded-xl p-3"><h3 className="font-black text-sm text-slate-800 mb-2">Quick Flags</h3><div className="space-y-1.5">{FLAGS.map(({flag,icon})=><div key={flag} className="flex items-center gap-2 text-[11px] text-slate-700"><span className="text-slate-500">{icon}</span><span>{flag}</span></div>)}</div></div>

      <div className="bg-white border-2 border-slate-300 rounded-xl overflow-hidden">
        <div className="px-3 py-2 bg-slate-900 text-white"><div className="text-xs font-black uppercase">Live Assignment Board</div><div className="text-[9px] text-slate-300">Click RN → click rooms. × unassigns.</div></div>
        <div className="divide-y divide-slate-100">
          {bedsideStaff.map(staff=>{const rooms=assignedRoomsFor(staff.id);const selected=manualStaffId===staff.id;const canAssign=['ACTIVE','RECALLED'].includes(staff.staffStatus);return <div key={staff.id} className={`p-2 ${selected?'bg-indigo-50':''}`}><button type="button" disabled={!canAssign} onClick={()=>selectStaff(staff)} className="w-full text-left disabled:opacity-50"><div className="flex justify-between gap-1"><span className={`text-xs font-black ${selected?'text-indigo-800':'text-slate-900'}`}>{firstName(staff.name)}{staff.role==='CHG'?' • CHG':''}</span><span className="text-[9px] text-slate-500">{rooms.length} pt</span></div></button><div className="flex flex-wrap gap-1 mt-1">{rooms.map(room=><span key={room.roomNumber} className={`inline-flex items-center rounded border text-[9px] font-black ${ACUITY_STYLES[room.acuity].badge}`}><button type="button" onClick={()=>setSelectedRoomNumber(room.roomNumber)} className="px-1.5 py-1">{room.roomNumber}</button><button type="button" title={`Unassign room ${room.roomNumber}`} onClick={()=>onAssignRoom(room.roomNumber,null)} className="px-1 py-1 border-l border-current/20 hover:bg-white/60">×</button></span>)}{rooms.length===0&&<span className="text-[9px] text-slate-400">—</span>}</div></div>;})}
        </div>
        <div className={`p-2 border-t ${unassignedRooms.length?'bg-rose-50 border-rose-200':'bg-emerald-50 border-emerald-200'}`}><div className={`text-[10px] font-black ${unassignedRooms.length?'text-rose-800':'text-emerald-800'}`}>NEEDS ASSIGNMENT ({unassignedRooms.length})</div><div className="flex flex-wrap gap-1 mt-1">{unassignedRooms.map(room=><button type="button" key={room.roomNumber} onClick={()=>setSelectedRoomNumber(room.roomNumber)} className="px-1.5 py-1 rounded border border-rose-300 bg-white text-[9px] font-black text-rose-800">{room.roomNumber}</button>)}{unassignedRooms.length===0&&<span className="text-[9px] font-bold text-emerald-700">All assigned ✓</span>}</div></div>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-[10px] leading-4 text-amber-950"><b>Unit rules</b><div>• HD only in ICU-capable rooms.</div><div>• 109/119 safety-preferred.</div><div>• Capability/workload before geography.</div></div>
    </aside>

    <section className="min-w-0 space-y-3">
      {manualStaff&&<div className="bg-indigo-50 border-2 border-indigo-400 rounded-xl px-4 py-3 flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black uppercase text-indigo-900">Rapid Manual Assignment</div><div className="text-sm text-indigo-900"><b>{firstName(manualStaff.name)}</b> selected — click occupied rooms in succession. Click one of her rooms again to unassign it.</div></div><button type="button" onClick={()=>setManualStaffId(null)} className="bg-white border border-indigo-300 rounded-lg px-3 py-2 text-xs font-bold text-indigo-800 flex items-center gap-1"><X className="w-3.5 h-3.5"/>Done</button></div>}
      <div className={`bg-white border rounded-xl overflow-hidden ${manualStaff?'border-indigo-300':'border-slate-200'}`}><div className="px-4 py-3 border-b border-slate-200 flex justify-between gap-2"><div><h2 className="font-black text-sm">1 East Floor Plan — Current Staffing</h2><p className="text-[11px] text-slate-500">{manualStaff?`Click rooms to assign to ${firstName(manualStaff.name)}.`:'Click a room to edit it. ✓ means assigned; red outline means assignment needed.'}</p></div><div className="text-[11px] text-slate-500">Selected: <b>{selectedRoom?.roomNumber||'—'}</b></div></div>
        <div className="relative bg-slate-50 overflow-hidden" style={{aspectRatio:'1365 / 1152'}}><img src={floorPlanImage} alt="1 East unit floor plan" className="absolute inset-0 w-full h-full object-contain opacity-75"/><div className="absolute left-[1.2%] top-[1.2%] text-[10px] font-black bg-white/90 rounded px-1.5 py-1 border">NORTH ↑</div>{currentShift.rooms.map(room=>{const pos=ROOM_POSITIONS[room.roomNumber];if(!pos)return null;const selected=room.roomNumber===selectedRoom?.roomNumber;const isUnassigned=room.isOccupied&&!room.assignedNurseId;const belongs=!!manualStaffId&&room.assignedNurseId===manualStaffId;const nurse=currentShift.roster.find(s=>s.id===room.assignedNurseId);const style=room.isOccupied?ACUITY_STYLES[room.acuity].room:'bg-white/85 border-slate-400 text-slate-500';return <button type="button" key={room.roomNumber} onClick={()=>handleRoomClick(room)} className={`absolute -translate-x-1/2 -translate-y-1/2 w-[5.8%] min-w-[44px] rounded-md border-2 shadow-sm px-1 py-1 text-center transition ${style} ${selected?'ring-4 ring-slate-900/25 z-20 scale-110':'z-10 hover:scale-105'} ${isUnassigned?'outline outline-4 outline-rose-500/70':''} ${belongs?'ring-4 ring-indigo-500/70 z-20':''}`} style={{left:`${pos.left}%`,top:`${pos.top}%`}}><div className="flex justify-center items-center gap-1"><span className="font-black text-[11px]">{room.roomNumber}</span>{room.isOccupied&&room.assignedNurseId&&<span className="text-[10px] font-black text-emerald-800">✓</span>}</div><div className="text-[8px] font-bold">{room.isOccupied?room.acuity:'EMPTY'}</div>{room.isOccupied&&<div className={`text-[8px] truncate ${isUnassigned?'font-black text-rose-800':''}`}>{nurse?firstName(nurse.name):'UNASSIGNED'}</div>}{room.flags.includes('Expected DC')&&<div className="text-[7px] font-black text-emerald-900">EXP DC</div>}{room.flags.includes('Possible DC')&&<div className="text-[7px] font-black text-amber-900">POSS DC</div>}</button>;})}</div>
      </div>
      <div className={`rounded-xl border p-3 ${unassignedRooms.length?'bg-rose-50 border-rose-300':'bg-emerald-50 border-emerald-300'}`}><div className="flex justify-between"><div><div className={`text-xs font-black uppercase ${unassignedRooms.length?'text-rose-900':'text-emerald-900'}`}>Rooms Needing Assignment</div><div className="text-[10px] text-slate-600">Occupied rooms only.</div></div><div className="text-lg font-black">{unassignedRooms.length}</div></div><div className="flex flex-wrap gap-1.5 mt-2">{unassignedRooms.map(room=><button key={room.roomNumber} onClick={()=>setSelectedRoomNumber(room.roomNumber)} className={`px-2 py-1.5 rounded-lg border text-[10px] font-black ${ACUITY_STYLES[room.acuity].badge}`}>{room.roomNumber} • {room.acuity}</button>)}{!unassignedRooms.length&&<span className="text-xs font-bold text-emerald-800">All occupied rooms assigned ✓</span>}</div></div>

      <div className="bg-white border border-slate-200 rounded-xl p-3"><div className="flex justify-between gap-2 mb-3"><div><h3 className="font-black text-sm">RN Assignments</h3><p className="text-[11px] text-slate-500">Click an RN name for rapid assignment, then click multiple rooms.</p></div><div className="text-[11px]">Patients <b>{occupiedRooms.length}</b> • Unassigned <b className="text-rose-700">{unassignedRooms.length}</b></div></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">{bedsideStaff.map(staff=>{const rooms=assignedRoomsFor(staff.id);const can=['ACTIVE','RECALLED'].includes(staff.staffStatus);const selected=manualStaffId===staff.id;return <div key={staff.id} className={`border-2 rounded-xl p-2.5 ${selected?'border-indigo-500 bg-indigo-50':'border-slate-200 bg-slate-50'}`}><div className="flex justify-between gap-2"><button disabled={!can} onClick={()=>selectStaff(staff)} className="text-left disabled:opacity-50"><div className="font-black text-sm">{firstName(staff.name)}</div><div className="text-[10px] text-slate-500">{staff.role} • {staff.capability} • {rooms.length} pt</div><div className={`text-[9px] font-black ${selected?'text-indigo-700':'text-blue-700'}`}>{selected?'SELECTED — CLICK ROOMS':can?'CLICK FOR RAPID ASSIGN':'NOT ACTIVE'}</div></button><select value={staff.staffStatus} onChange={e=>onStaffStatusChange(staff,e.target.value as StaffStatus)} className={`text-[9px] font-black border rounded-md px-1 ${STATUS_STYLES[staff.staffStatus]}`}><option value="ACTIVE">ACTIVE</option><option value="FLEXED">FLEXED</option><option value="ON_CALL">ON CALL</option><option value="RECALLED">RECALLED</option></select></div><div className="flex flex-wrap gap-1 mt-2">{rooms.map(room=><span key={room.roomNumber} className={`inline-flex rounded border text-[9px] font-black ${ACUITY_STYLES[room.acuity].badge}`}><button onClick={()=>setSelectedRoomNumber(room.roomNumber)} className="px-1.5 py-1">{room.roomNumber}</button><button title="Unassign" onClick={()=>onAssignRoom(room.roomNumber,null)} className="px-1 border-l border-current/20">×</button></span>)}</div></div>;})}</div></div>
    </section>

    <aside className="bg-white border border-slate-200 rounded-xl p-4 2xl:sticky 2xl:top-4">{selectedRoom?<><div className="flex justify-between border-b pb-3"><div><div className="text-xl font-black">Room {selectedRoom.roomNumber}</div><div className="text-[11px] text-slate-500">Live room detail</div></div><label className="flex items-center gap-2 text-[10px] font-bold"><input type="checkbox" checked={selectedRoom.isOccupied} onChange={e=>onRoomChange({...selectedRoom,isOccupied:e.target.checked,assignedNurseId:e.target.checked?selectedRoom.assignedNurseId:null})}/>Occupied</label></div>
      <div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500 block mb-1">Acuity / Level of Care</label><select value={selectedRoom.acuity} onChange={e=>setSelectedAcuity(e.target.value as AcuityLevel)} className={`w-full border rounded-lg px-3 py-2 text-sm font-black ${ACUITY_STYLES[selectedRoom.acuity].badge}`}><option>CVICU</option><option>ICU</option><option>PCU</option><option>TELE</option></select></div>
      <div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500 block mb-1">Assigned RN</label><select value={selectedRoom.assignedNurseId||''} onChange={e=>onAssignRoom(selectedRoom.roomNumber,e.target.value||null)} className="w-full border rounded-lg px-3 py-2 text-sm"><option value="">Unassigned</option>{bedsideStaff.map(staff=><option key={staff.id} value={staff.id}>{firstName(staff.name)} — {staff.role} / {staff.capability} / {staff.staffStatus}</option>)}</select>{assignedNurse&&<div className="mt-1 text-[10px] text-slate-500">Current: <b>{assignedNurse.name}</b> • {assignedNurse.assignedPhone||'No phone'}</div>}</div>
      <div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500 block mb-1">Non-PHI Stay Token</label><input value={selectedRoom.patientStayId} onChange={e=>onRoomChange({...selectedRoom,patientStayId:e.target.value})} className="w-full border rounded-lg px-3 py-2 text-sm" placeholder="Optional continuity token"/></div>
      <div className="mt-4"><div className="text-xs font-black mb-2">Quick Flags</div><div className="grid grid-cols-2 gap-1.5">{FLAGS.map(({flag,icon})=>{const active=selectedRoom.flags.includes(flag);return <button key={flag} onClick={()=>toggleFlag(flag)} className={`min-h-9 flex items-center gap-1.5 px-2 py-1.5 rounded-lg border text-[10px] font-bold text-left ${active?'bg-blue-50 border-blue-400 text-blue-800':'bg-slate-50 border-slate-200 text-slate-600'}`}>{icon}<span>{flag}</span></button>;})}</div><div className="mt-2 text-[9px] text-slate-500">Possible DC is informational. Expected DC automatically reduces projected census in the Operational Snapshot.</div></div>
      <div className="mt-4 pt-3 border-t"><div className="text-xs font-black">Room notes</div><div className="mt-1 text-[10px] text-slate-500">{['109','119'].includes(selectedRoom.roomNumber)?'Safety-preferred room near nursing station.':'No special safety-room preference.'}</div></div>
    </>:<div className="text-sm text-slate-500">Select a room.</div>}</aside>
  </div></div>;
};
