import React, { useMemo, useState } from 'react';
import { Activity, AlertTriangle, Brain, CircleDot, Droplets, HeartPulse, LogIn, LogOut, MoveRight, ShieldAlert, Users, Wind, X, Ban } from 'lucide-react';
import floorPlanImage from '../assets/1e-floorplan.png';
import { AcuityLevel, ComplexityFlag, CurrentShiftState, NurseStaff, PatientRoom, StaffStatus } from '../types';
import { RapidRoomTools } from './RapidRoomTools';

interface Props { currentShift: CurrentShiftState; onRoomChange: (room: PatientRoom) => void; onAssignRoom: (roomNumber: string, nurseId: string | null) => void; onStaffStatusChange: (staff: NurseStaff, status: StaffStatus) => void; }
type RoomPosition={left:number;top:number};
const ROOM_POSITIONS:Record<string,RoomPosition>={
'101':{left:85.2,top:88.5},'102':{left:85.2,top:74.2},'103':{left:85.2,top:61.4},'104':{left:85.2,top:48.0},'105':{left:85.2,top:35.5},'106':{left:85.2,top:17.4},
'107':{left:54.3,top:24.0},'108':{left:54.3,top:33.8},'109':{left:51.4,top:40.8},'110':{left:58.8,top:59.0},'111':{left:58.8,top:70.0},'112':{left:58.8,top:78.6},'113':{left:57.2,top:88.5},
'114':{left:17.2,top:88.4},'115':{left:17.2,top:78.2},'116':{left:17.2,top:68.4},'117':{left:17.2,top:59.0},'118':{left:17.2,top:50.4},'119':{left:17.2,top:40.7},'120':{left:17.2,top:33.0},'121':{left:17.2,top:24.0},'122':{left:17.2,top:14.8}};
const ACUITY_STYLES:Record<AcuityLevel,{badge:string;room:string}>={CVICU:{badge:'bg-rose-100 text-rose-800 border-rose-200',room:'bg-rose-200/90 border-rose-500 text-rose-950'},ICU:{badge:'bg-orange-100 text-orange-800 border-orange-200',room:'bg-orange-200/90 border-orange-500 text-orange-950'},PCU:{badge:'bg-blue-100 text-blue-800 border-blue-200',room:'bg-blue-200/90 border-blue-500 text-blue-950'},TELE:{badge:'bg-emerald-100 text-emerald-800 border-emerald-200',room:'bg-emerald-200/90 border-emerald-500 text-emerald-950'}};
const FLAGS:{flag:ComplexityFlag;label:string;icon:React.ReactNode}[]=[
{flag:'Vent',label:'Vent',icon:<Wind className="w-3.5 h-3.5"/>},{flag:'Pressors',label:'Pressors',icon:<Activity className="w-3.5 h-3.5"/>},{flag:'Impella/IABP',label:'Impella/IABP',icon:<HeartPulse className="w-3.5 h-3.5"/>},{flag:'Fresh Post-Op',label:'Fresh Post Op',icon:<CircleDot className="w-3.5 h-3.5"/>},{flag:'HD/Dialysis',label:'HD/Dialysis',icon:<Droplets className="w-3.5 h-3.5"/>},{flag:'Isolation',label:'Isolation',icon:<ShieldAlert className="w-3.5 h-3.5"/>},{flag:'Sitter/Safety',label:'Sitter/Safety',icon:<Users className="w-3.5 h-3.5"/>},{flag:'High Fall Risk',label:'High Fall Risk',icon:<AlertTriangle className="w-3.5 h-3.5"/>},{flag:'Confused',label:'Confused',icon:<Brain className="w-3.5 h-3.5"/>},{flag:'Admission',label:'Recent Admission',icon:<LogIn className="w-3.5 h-3.5"/>},{flag:'Transfer',label:'Pending Transfer',icon:<MoveRight className="w-3.5 h-3.5"/>},{flag:'Possible DC',label:'Possible DC',icon:<LogOut className="w-3.5 h-3.5"/>},{flag:'Expected DC',label:'Expected DC',icon:<LogOut className="w-3.5 h-3.5"/>},{flag:'BLOCKED',label:'BLOCKED',icon:<Ban className="w-3.5 h-3.5"/>},{flag:'Discharge',label:'Discharge',icon:<LogOut className="w-3.5 h-3.5"/>}];
const firstName=(name:string)=>name.trim().split(/\s+/)[0]||name;
const pairLabel=(staff:NurseStaff,roster:NurseStaff[])=>{if(staff.role!=='Preceptor'||!staff.orientationPartnerId)return firstName(staff.name);const p=roster.find(x=>x.id===staff.orientationPartnerId);return p?`${firstName(staff.name)} / ${firstName(p.name)}`:firstName(staff.name);};

export const FloorPlanCurrentStaffing:React.FC<Props>=({currentShift,onRoomChange,onAssignRoom})=>{
 const occupied=currentShift.rooms.filter(r=>r.isOccupied),unassigned=occupied.filter(r=>!r.assignedNurseId);
 const [selectedRoomNumber,setSelectedRoomNumber]=useState(occupied[0]?.roomNumber||'101');const [manualStaffId,setManualStaffId]=useState<string|null>(null);
 const selectedRoom=currentShift.rooms.find(r=>r.roomNumber===selectedRoomNumber)||currentShift.rooms[0];const assignedNurse=currentShift.roster.find(s=>s.id===selectedRoom?.assignedNurseId);const manualStaff=currentShift.roster.find(s=>s.id===manualStaffId)||null;
 const bedside=useMemo(()=>currentShift.roster.filter(s=>['RN','CHG','Preceptor'].includes(s.role)),[currentShift.roster]);
 const setAcuity=(a:AcuityLevel)=>selectedRoom&&onRoomChange({...selectedRoom,acuity:a,isOccupied:true});
 const toggleFlag=(flag:ComplexityFlag)=>{if(!selectedRoom)return;const exists=selectedRoom.flags.includes(flag);let flags=exists?selectedRoom.flags.filter(f=>f!==flag):[...selectedRoom.flags,flag];if(!exists&&flag==='Expected DC')flags=flags.filter(f=>f!=='Possible DC');if(!exists&&flag==='Possible DC')flags=flags.filter(f=>f!=='Expected DC');onRoomChange({...selectedRoom,flags});};
 const roomsFor=(id:string)=>currentShift.rooms.filter(r=>r.isOccupied&&r.assignedNurseId===id);
 const selectStaff=(s:NurseStaff)=>{if(!['ACTIVE','RECALLED'].includes(s.staffStatus))return;setManualStaffId(manualStaffId===s.id?null:s.id);};
 const roomClick=(r:PatientRoom)=>{setSelectedRoomNumber(r.roomNumber);if(manualStaffId&&r.isOccupied)onAssignRoom(r.roomNumber,r.assignedNurseId===manualStaffId?null:manualStaffId);};
 return <div className="grid grid-cols-1 2xl:grid-cols-[230px_minmax(0,1fr)_300px] gap-4 items-start">
  <aside className="space-y-3"><RapidRoomTools rooms={currentShift.rooms} onRoomChange={onRoomChange}/>
   <div className="bg-white border-2 border-slate-300 rounded-xl overflow-hidden"><div className="px-3 py-2 bg-slate-900 text-white"><div className="text-xs font-black uppercase">Live Assignment Board</div><div className="text-[9px] text-slate-300">Click RN → click rooms. × unassigns.</div></div><div className="divide-y divide-slate-100">{bedside.map(staff=>{const rs=roomsFor(staff.id),sel=manualStaffId===staff.id,can=['ACTIVE','RECALLED'].includes(staff.staffStatus);return <div key={staff.id} className={`p-2 ${sel?'bg-indigo-50':''}`}><button disabled={!can} onClick={()=>selectStaff(staff)} className="w-full text-left disabled:opacity-50"><div className="flex justify-between"><span className={`text-xs font-black ${sel?'text-indigo-800':'text-slate-900'}`}>{pairLabel(staff,currentShift.roster)}{staff.role==='CHG'?' • CHG':''}</span><span className="text-[9px] text-slate-500">{rs.length} pt</span></div></button><div className="flex flex-wrap gap-1 mt-1">{rs.map(r=><span key={r.roomNumber} className={`inline-flex rounded border text-[9px] font-black ${ACUITY_STYLES[r.acuity].badge}`}><button onClick={()=>setSelectedRoomNumber(r.roomNumber)} className="px-1.5 py-1">{r.roomNumber}</button><button onClick={()=>onAssignRoom(r.roomNumber,null)} className="px-1 border-l border-current/20">×</button></span>)}{!rs.length&&<span className="text-[9px] text-slate-400">—</span>}</div></div>})}</div><div className={`p-2 border-t ${unassigned.length?'bg-rose-50':'bg-emerald-50'}`}><div className={`text-[10px] font-black ${unassigned.length?'text-rose-800':'text-emerald-800'}`}>NEEDS ASSIGNMENT ({unassigned.length})</div><div className="flex flex-wrap gap-1 mt-1">{unassigned.map(r=><button key={r.roomNumber} onClick={()=>setSelectedRoomNumber(r.roomNumber)} className="px-1.5 py-1 rounded border border-rose-300 bg-white text-[9px] font-black text-rose-800">{r.roomNumber}</button>)}{!unassigned.length&&<span className="text-[9px] font-bold text-emerald-700">All assigned ✓</span>}</div></div></div>
  </aside>
  <section className="min-w-0 space-y-3">{manualStaff&&<div className="bg-indigo-50 border-2 border-indigo-400 rounded-xl px-4 py-3 flex justify-between gap-3"><div><div className="text-xs font-black uppercase text-indigo-900">Rapid Manual Assignment</div><div className="text-sm text-indigo-900"><b>{pairLabel(manualStaff,currentShift.roster)}</b> selected — click occupied rooms in succession.</div></div><button onClick={()=>setManualStaffId(null)} className="bg-white border border-indigo-300 rounded-lg px-3 py-2 text-xs font-bold text-indigo-800 flex items-center gap-1"><X className="w-3.5 h-3.5"/>Done</button></div>}
   <div className="bg-white border border-slate-200 rounded-xl overflow-hidden"><div className="px-4 py-3 border-b flex justify-between"><div><h2 className="font-black text-sm">1 East Floor Plan — Current Staffing</h2><p className="text-[11px] text-slate-500">✓ assigned • red outline needs assignment • use Rapid Room Coding for acuity/flags.</p></div><div className="text-[11px] text-slate-500">Selected: <b>{selectedRoom?.roomNumber}</b></div></div><div className="relative bg-slate-50 overflow-hidden" style={{aspectRatio:'1365 / 1152'}}><img src={floorPlanImage} alt="1 East unit floor plan" className="absolute inset-0 w-full h-full object-contain opacity-75"/>{currentShift.rooms.map(r=>{const pos=ROOM_POSITIONS[r.roomNumber];if(!pos)return null;const nurse=currentShift.roster.find(s=>s.id===r.assignedNurseId),need=r.isOccupied&&!r.assignedNurseId,sel=r.roomNumber===selectedRoom?.roomNumber,belongs=!!manualStaffId&&r.assignedNurseId===manualStaffId,style=r.isOccupied?ACUITY_STYLES[r.acuity].room:'bg-white/90 border-slate-400 text-slate-500';return <button key={r.roomNumber} onClick={()=>roomClick(r)} className={`absolute -translate-x-1/2 -translate-y-1/2 w-[5.7%] min-w-[44px] rounded-md border-2 shadow-sm px-1 py-1 text-center ${style} ${sel?'ring-4 ring-slate-900/20 z-20':'z-10'} ${need?'outline outline-4 outline-rose-500/70':''} ${belongs?'ring-4 ring-indigo-500/70':''}`} style={{left:`${pos.left}%`,top:`${pos.top}%`}}><div className="font-black text-[11px]">{r.roomNumber}{r.isOccupied&&r.assignedNurseId?' ✓':''}</div><div className="text-[8px] font-bold">{r.isOccupied?r.acuity:'EMPTY'}</div>{r.isOccupied&&<div className={`text-[8px] truncate ${need?'font-black text-rose-800':''}`}>{nurse?pairLabel(nurse,currentShift.roster):'UNASSIGNED'}</div>}{r.flags.includes('BLOCKED')&&<div className="text-[7px] font-black text-rose-900">BLOCKED</div>}</button>})}</div></div>
   <div className={`rounded-xl border p-3 ${unassigned.length?'bg-rose-50 border-rose-300':'bg-emerald-50 border-emerald-300'}`}><div className="flex justify-between"><div><div className="text-xs font-black uppercase">Rooms Needing Assignment</div><div className="text-[10px] text-slate-600">Occupied rooms only.</div></div><div className="text-lg font-black">{unassigned.length}</div></div><div className="flex flex-wrap gap-1 mt-2">{unassigned.map(r=><button key={r.roomNumber} onClick={()=>setSelectedRoomNumber(r.roomNumber)} className={`px-2 py-1 rounded border text-[10px] font-black ${ACUITY_STYLES[r.acuity].badge}`}>{r.roomNumber} • {r.acuity}</button>)}</div></div>
  </section>
  <aside className="bg-white border border-slate-200 rounded-xl p-4 2xl:sticky 2xl:top-4">{selectedRoom&&<><div className="flex justify-between border-b pb-3"><div><div className="text-xl font-black">Room {selectedRoom.roomNumber}</div><div className="text-[11px] text-slate-500">Live room detail</div></div><label className="text-[10px] font-bold"><input type="checkbox" checked={selectedRoom.isOccupied} onChange={e=>onRoomChange({...selectedRoom,isOccupied:e.target.checked,assignedNurseId:e.target.checked?selectedRoom.assignedNurseId:null})}/> Occupied</label></div><div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500">Acuity</label><select value={selectedRoom.acuity} onChange={e=>setAcuity(e.target.value as AcuityLevel)} className={`w-full border rounded-lg px-3 py-2 text-sm font-black ${ACUITY_STYLES[selectedRoom.acuity].badge}`}><option>CVICU</option><option>ICU</option><option>PCU</option><option>TELE</option></select></div><div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500">Assigned RN</label><select value={selectedRoom.assignedNurseId||''} onChange={e=>onAssignRoom(selectedRoom.roomNumber,e.target.value||null)} className="w-full border rounded-lg px-3 py-2 text-sm"><option value="">Unassigned</option>{bedside.map(s=><option key={s.id} value={s.id}>{pairLabel(s,currentShift.roster)} — {s.capability} / {s.staffStatus}</option>)}</select>{assignedNurse&&<div className="text-[10px] text-slate-500 mt-1">Current: <b>{pairLabel(assignedNurse,currentShift.roster)}</b></div>}</div><div className="mt-3"><label className="text-[10px] uppercase font-black text-slate-500">Non-PHI Stay Token</label><input value={selectedRoom.patientStayId} onChange={e=>onRoomChange({...selectedRoom,patientStayId:e.target.value})} className="w-full border rounded-lg px-3 py-2 text-sm"/></div><div className="mt-4"><div className="text-xs font-black mb-2">Quick Flags</div><div className="grid grid-cols-2 gap-1.5">{FLAGS.map(({flag,label,icon})=><button key={flag} onClick={()=>toggleFlag(flag)} className={`min-h-9 flex items-center gap-1.5 px-2 py-1.5 rounded-lg border text-[10px] font-bold text-left ${selectedRoom.flags.includes(flag)?'bg-blue-50 border-blue-400 text-blue-800':'bg-slate-50 border-slate-200 text-slate-600'}`}>{icon}<span>{label}</span></button>)}</div></div></>}
  </aside>
 </div>;
};
