import React from 'react';
import { FinalizedShiftSnapshot, NurseStaff, PatientRoom, OnCallProviders } from '../types';
interface PrintSheetProps { date:string; shiftType:string; roster:NurseStaff[]; rooms:PatientRoom[]; onCall:OnCallProviders; previousShift?:FinalizedShiftSnapshot|null; }
const first=(n:string)=>n.trim().split(/\s+/)[0]||n;
const pairName=(s:NurseStaff,roster:NurseStaff[])=>{if(s.role!=='Preceptor'||!s.orientationPartnerId)return first(s.name);const p=roster.find(x=>x.id===s.orientationPartnerId);return p?`${first(s.name)} / ${first(p.name)}`:first(s.name);};
const rows=(roster:NurseStaff[],rooms:PatientRoom[])=>roster.filter(s=>s.role!=='Orientee').map(s=>{const assigned=rooms.filter(r=>r.assignedNurseId===s.id).map(r=>r.roomNumber).sort();let assignment=s.role==='CHG'?(assigned.length?`CHG, ${assigned.join(', ')}`:'CHG'):s.role==='MT'?'MT':s.role==='PCT'?'PCT':s.staffStatus==='FLEXED'?'FLEXED':s.staffStatus==='ON_CALL'?'ON CALL':assigned.length?assigned.join(', '):'—';return {id:s.id,name:pairName(s,roster),assignment,phone:s.assignedPhone||'-'};});
export const PrintSheet:React.FC<PrintSheetProps>=({date,shiftType,roster,rooms,onCall,previousShift})=>{const current=rows(roster,rooms),previous=previousShift?rows(previousShift.roster,previousShift.rooms):[];const max=Math.max(current.length,previous.length,1);return <div className="bg-white text-black p-4 font-sans max-w-5xl mx-auto print:p-0">
 <div className="border-b-2 border-black pb-1 mb-2 flex justify-between items-end"><div><h1 className="text-xl font-black">1 EAST STAFFING ASSIGNMENTS</h1><p className="text-xs font-semibold">Cardiac Universal Bed (CUB) Unit • Shift Handoff Reference</p></div><div className="text-right text-sm font-bold">{date}<div>{shiftType} Shift</div></div></div>
 <table className="w-full border-collapse border border-black text-[11px]"><thead><tr><th colSpan={3} className="border border-black p-1 bg-neutral-200 text-left">PREVIOUS SHIFT / HANDOFF FROM</th><th colSpan={3} className="border border-black p-1 bg-neutral-200 text-left">CURRENT SHIFT / HANDOFF TO</th></tr><tr><th className="border border-black p-1 text-left">Staff</th><th className="border border-black p-1 text-left">Assignment</th><th className="border border-black p-1 text-left">Phone</th><th className="border border-black p-1 text-left">Staff</th><th className="border border-black p-1 text-left">Assignment</th><th className="border border-black p-1 text-left">Phone</th></tr></thead><tbody>{Array.from({length:max}).map((_,i)=>{const p=previous[i],c=current[i];return <tr key={i}><td className="border border-black p-1 font-bold">{p?.name||''}</td><td className="border border-black p-1">{p?.assignment||''}</td><td className="border border-black p-1">{p?.phone||''}</td><td className="border border-black p-1 font-bold">{c?.name||''}</td><td className="border border-black p-1">{c?.assignment||''}</td><td className="border border-black p-1">{c?.phone||''}</td></tr>})}</tbody></table>
 <div className="border border-black border-t-0 p-2 text-[10px]"><div className="font-black mb-1">ON-CALL PROVIDERS</div><div className="grid grid-cols-5 gap-2"><div><b>INTENSIVIST</b><br/>{onCall.intensivist||'-'}</div><div><b>CARDIOTHORACIC</b><br/>{onCall.cardiothoracic||'-'}</div><div><b>ACUTE MI</b><br/>{onCall.acuteMI||'-'}</div><div><b>CARDIOLOGY</b><br/>{onCall.cardiology||'-'}</div><div><b>HOSPITALIST</b><br/>{onCall.hospitalist||'-'}</div></div></div>
 </div>;
};
