import React, { useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, Copy, Play, Save, Sparkles, Users, Settings2 } from 'lucide-react';
import { AssignmentWarning, CurrentShiftState, NurseStaff, OnCallProviders, PatientRoom, MTCoverageState, PCTCoverageState } from '../types';
import { runRecommendationEngine } from '../services/recommendationEngine';
import { postProcessRecommendation } from '../services/recommendationPostProcessor';
import { StorageService } from '../services/storage';
import { FloorPlanCurrentStaffing } from './FloorPlanCurrentStaffing';
import { RecommendationOption, RecommendationOptions } from './RecommendationOptions';

interface Props {
 date:string; shiftType:'Day'|'Night'; roster:NurseStaff[]; rooms:PatientRoom[]; mtState:MTCoverageState; pctState:PCTCoverageState; onCall:OnCallProviders; sourceShift:CurrentShiftState;
 onDateChange:(value:string)=>void; onShiftTypeChange:(value:'Day'|'Night')=>void; onRosterChange:(value:NurseStaff[])=>void; onRoomsChange:(value:PatientRoom[])=>void;
 onMtStateChange:(value:MTCoverageState)=>void; onPctStateChange:(value:PCTCoverageState)=>void; onSaveBaseline:()=>void;
}
const normalizedName=(name:string)=>name.trim().toLowerCase().replace(/\s+/g,' ');
const canTakeLoad=(s:NurseStaff)=>['CHG','RN','Preceptor'].includes(s.role)&&['ACTIVE','RECALLED'].includes(s.staffStatus);

export const TomorrowStaffing:React.FC<Props>=({date,shiftType,roster,rooms,mtState,pctState,onCall,sourceShift,onDateChange,onShiftTypeChange,onRosterChange,onRoomsChange,onMtStateChange,onPctStateChange,onSaveBaseline})=>{
 const[warnings,setWarnings]=useState<AssignmentWarning[]>([]),[unassigned,setUnassigned]=useState<string[]>([]),[fitLabel,setFitLabel]=useState('NOT RUN'),[recommendationOptions,setRecommendationOptions]=useState<RecommendationOption[]>([]),[semiAutoActive,setSemiAutoActive]=useState(false),[carryMessage,setCarryMessage]=useState(''),[lockedNurseIds,setLockedNurseIds]=useState<string[]>([]);
 const toggleLock=(nurseId:string)=>setLockedNurseIds(current=>current.includes(nurseId)?current.filter(id=>id!==nurseId):[...current,nurseId]);
 const census=rooms.filter(r=>r.isOccupied).length,activeRNs=roster.filter(s=>['RN','Preceptor'].includes(s.role)&&['ACTIVE','RECALLED'].includes(s.staffStatus)).length,liveUnassigned=rooms.filter(r=>r.isOccupied&&!r.assignedNurseId).length;
 const rosterNames=Object.fromEntries(roster.map(s=>[s.id,s.name]));
 const fixedAssignments=Object.fromEntries(rooms.filter(r=>r.isOccupied&&r.assignedNurseId).map(r=>[r.roomNumber,r.assignedNurseId as string]));const fixedRoomNumbers=Object.keys(fixedAssignments);
 const pseudoShift:CurrentShiftState=useMemo(()=>({date,shiftType,roster,rooms,mtState,pctState,onCall,lastUpdatedAt:new Date().toISOString()}),[date,shiftType,roster,rooms,mtState,pctState,onCall]);
 const updateRoom=(u:PatientRoom)=>onRoomsChange(rooms.map(r=>r.roomNumber===u.roomNumber?u:r));
 const assignRoom=(roomNumber:string,nurseId:string|null)=>{onRoomsChange(rooms.map(r=>r.roomNumber===roomNumber?{...r,assignedNurseId:nurseId}:r));setRecommendationOptions([]);setCarryMessage('')};
 const updateStatus=(staff:NurseStaff,status:NurseStaff['staffStatus'])=>onRosterChange(roster.map(s=>s.id===staff.id?{...s,staffStatus:status}:s));
 const resetContext=()=>{setCarryMessage('');setRecommendationOptions([]);setWarnings([]);setUnassigned([]);setFitLabel('NOT RUN')};
 const carryCurrentRoomCoding=()=>{const src=Object.fromEntries(sourceShift.rooms.map(r=>[r.roomNumber,r]));onRoomsChange(rooms.map(room=>{const s=src[room.roomNumber];return s?{...room,isOccupied:s.isOccupied,acuity:s.acuity,acuityConfirmed:s.acuityConfirmed,flags:[...s.flags],patientStayId:s.patientStayId,assignedNurseId:null}:room}));resetContext();setFitLabel('ROOM CODING CARRIED');setCarryMessage('Current room status, acuity and flags carried into the Next Shift Plan. RN assignments left blank.')};
 const carryCurrentGroupings=()=>{const srcRooms=Object.fromEntries(sourceShift.rooms.map(r=>[r.roomNumber,r])),srcStaff=Object.fromEntries(sourceShift.roster.map(s=>[s.id,s]));let carried=0;const next=rooms.map(room=>{if(!room.isOccupied)return{...room,assignedNurseId:null};const sr=srcRooms[room.roomNumber];if(!sr?.assignedNurseId)return{...room,assignedNurseId:null};const ss=srcStaff[sr.assignedNurseId];if(!ss)return{...room,assignedNurseId:null};const target=roster.find(s=>s.id===ss.id&&canTakeLoad(s))||roster.find(s=>normalizedName(s.name)===normalizedName(ss.name)&&canTakeLoad(s));if(!target)return{...room,assignedNurseId:null};carried++;return{...room,assignedNurseId:target.id}});onRoomsChange(next);resetContext();setFitLabel(`CARRIED ${carried}`);setCarryMessage(`Carried ${carried} compatible current-shift room assignment${carried===1?'':'s'}. Edit directly, then Semi-Auto Fill Rest if desired.`)};
 const recallPreviousAssignments=()=>{};
 const recommend=(strategy:'BALANCED'|'CONSERVE_SKILL_MIX'|'CAPACITY_EXCEPTION',charge:boolean,quad:boolean,fixed:Record<string,string>={})=>postProcessRecommendation(runRecommendationEngine(roster,rooms,charge,quad,strategy,fixed,lockedNurseIds),roster,rooms,Object.keys(fixed),lockedNurseIds);
 const generate=(semi=false)=>{const fixed=semi?fixedAssignments:{};const balanced=recommend('BALANCED',false,false,fixed),conserve=recommend('CONSERVE_SKILL_MIX',false,false,fixed),normal=recommend('CAPACITY_EXCEPTION',false,false,fixed),capacity=normal.unassignedRooms.length===0?normal:recommend('CAPACITY_EXCEPTION',true,true,fixed);const prefix=semi&&fixedRoomNumbers.length?`Preserves ${fixedRoomNumbers.length} CN pre-assigned room${fixedRoomNumbers.length===1?'':'s'}, then `:'';setRecommendationOptions([{id:'BALANCED',title:'Balanced / Spread ICU',subtitle:`${prefix}fills remaining rooms using acuity, workload and geography.`,result:balanced},{id:'CONSERVE_SKILL_MIX',title:'Preserve Critical-Care Skill Mix',subtitle:`${prefix}fills remaining rooms while preserving critical-care skill mix.`,result:conserve},{id:'CAPACITY_EXCEPTION',title:'Capacity Exception',subtitle:`${prefix}uses capacity exceptions only when necessary.`,result:capacity}]);setSemiAutoActive(semi);setFitLabel(semi?`SEMI-AUTO • ${fixedRoomNumbers.length} FIXED`:'3 OPTIONS');setWarnings([]);setUnassigned([])};
 const applyOption=(o:RecommendationOption)=>{const r=o.result;onRoomsChange(rooms.map(room=>({...room,assignedNurseId:r.assignments[room.roomNumber]||null})));setWarnings(r.warnings);setUnassigned(r.unassignedRooms);setFitLabel(r.fitLabel);setRecommendationOptions([]);setSemiAutoActive(false)};
 return <div className="space-y-3">
  <div className="bg-white border rounded-xl px-3 py-2 flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-3"><div><div className="text-[10px] font-black uppercase text-slate-500">Next Shift Quick Assignment</div><div className="text-sm font-black">{date} • {shiftType} Shift</div></div><div className="text-xs bg-slate-100 rounded px-2 py-1">Planned Census <b>{census}</b></div><div className="text-xs bg-slate-100 rounded px-2 py-1">RNs <b>{activeRNs}</b></div><div className={`text-xs rounded px-2 py-1 ${liveUnassigned?'bg-rose-100 text-rose-800':'bg-emerald-100 text-emerald-800'}`}>Needs RN <b>{liveUnassigned}</b></div></div><div className="flex gap-2"><button onClick={onSaveBaseline} className="bg-blue-600 text-white px-3 py-1.5 rounded-lg text-xs font-bold flex gap-1"><Save className="w-3.5"/>Save Plan</button></div></div>
  <FloorPlanCurrentStaffing quickMode currentShift={pseudoShift} onRoomChange={updateRoom} onAssignRoom={assignRoom} onStaffStatusChange={updateStatus} onRecallPrevious={recallPreviousAssignments} lockedNurseIds={lockedNurseIds} onToggleLock={toggleLock}/>
  <details className="bg-white rounded-xl border p-3"><summary className="font-black text-xs uppercase cursor-pointer flex items-center gap-2"><Settings2 className="w-4"/>More tools / planning</summary><div className="mt-4 space-y-3">
   <div className="flex flex-wrap gap-3 items-end"><div><label className="text-[10px] uppercase font-black text-slate-500 block">Next Shift Date</label><input type="date" value={date} onChange={e=>{onDateChange(e.target.value);resetContext()}} className="border rounded-lg px-3 py-2 text-xs"/></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">Shift</label><select value={shiftType} onChange={e=>{onShiftTypeChange(e.target.value as 'Day'|'Night');resetContext()}} className="border rounded-lg px-3 py-2 text-xs"><option value="Day">Day</option><option value="Night">Night</option></select></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">MT Coverage</label><select value={mtState} onChange={e=>onMtStateChange(e.target.value as MTCoverageState)} className="border rounded-lg px-3 py-2 text-xs"><option value="MT_PRESENT">MT Present</option><option value="RN_COVERING_MT">RN Covering MT</option><option value="MT_UNFILLED">MT Unfilled</option></select></div><div><label className="text-[10px] uppercase font-black text-slate-500 block">PCT Support</label><select value={pctState} onChange={e=>onPctStateChange(e.target.value as PCTCoverageState)} className="border rounded-lg px-3 py-2 text-xs"><option value="PCT_PRESENT">PCT Present</option><option value="PCT_NONE">No PCT</option></select></div></div>
   <div className="flex flex-wrap gap-2"><button onClick={carryCurrentRoomCoding} className="bg-slate-700 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Copy className="w-3.5"/>Carry Room Coding</button><button onClick={carryCurrentGroupings} className="bg-slate-700 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Users className="w-3.5"/>Carry Assignment Groupings</button><button onClick={()=>generate(false)} className="bg-emerald-600 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Play className="w-3.5"/>Generate 3 Options</button><button onClick={()=>generate(true)} className="bg-indigo-600 text-white px-3 py-2 rounded-lg text-xs font-black flex gap-1"><Sparkles className="w-3.5"/>Semi-Auto Fill Rest{fixedRoomNumbers.length?` (${fixedRoomNumbers.length})`:''}{lockedNurseIds.length?` · ${lockedNurseIds.length}\u{1F512}`:''}</button></div>
   {carryMessage&&<div className="bg-blue-50 border border-blue-200 rounded-lg px-3 py-2 text-xs text-blue-900">{carryMessage}</div>}<RecommendationOptions options={recommendationOptions} rosterNames={rosterNames} onApply={applyOption}/>{unassigned.length>0&&<div className="bg-rose-50 border border-rose-300 text-rose-900 rounded-xl p-3 flex gap-2"><AlertTriangle className="w-4"/><b className="text-sm">Recommendation needs CN review for {unassigned.join(', ')}.</b></div>}<div className="text-[10px] text-slate-500">Recommendation status: {fitLabel}{semiAutoActive?' • Semi-Auto preview':''}</div>
  </div></details>
 </div>;
};